# Generated by Django 5.0.2 on 2024-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_distance',
            field=models.IntegerField(default=1000, verbose_name='Maksymalna odległość pieszo'),
        ),
        migrations.AddField(
            model_name='user',
            name='pace',
            field=models.FloatField(default=1.4, verbose_name='Prędkość chodzenia'),
        ),
    ]
