version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    restart: always

  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      ./data/main/osrm:/data

  django:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      ./data/main/transit.db:/app/transit.db
    ports:
      - "8000:8000"
    depends_on:
      - osrm
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
