version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    restart: always

  osrm_pl_malopolskie:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/pl_malopolskie:/data:ro

  osrm_pl_mazowieckie:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/pl_mazowieckie:/data:ro

  osrm_pl_wielkopolskie:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/pl_wielkopolskie:/data:ro

  osrm_es_madrid:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/es_madrid:/data:ro

  osrm_na_canada_quebec:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/na_canada_quebec:/data:ro

  osrm_na_canada_ontario:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/na_canada_ontario:/data:ro

  osrm_it_centro:
    image: ghcr.io/project-osrm/osrm-backend
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - ./data/regions/it_centro:/data:ro

  django:
    build:
      context: ./ebus
      dockerfile: Dockerfile
    volumes:
      - ./data:/data:ro
      - ./cities.json:/ebus/cities.json:ro
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      OSRM_URL_pl_malopolskie: "http://osrm_pl_malopolskie:5000"
      OSRM_URL_pl_mazowieckie: "http://osrm_pl_mazowieckie:5000"
      OSRM_URL_pl_wielkopolskie: "http://osrm_pl_wielkopolskie:5000"
      OSRM_URL_es_madrid: "http://osrm_es_madrid:5000"
      OSRM_URL_na_canada_quebec: "http://osrm_na_canada_quebec:5000"
      OSRM_URL_na_canada_ontario: "http://osrm_na_canada_ontario:5000"


volumes:
  postgres_data:
