# Generated by Django 5.0.2 on 2024-11-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_realtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripupdate',
            name='arrival_time',
        ),
    ]
