# Generated by Django 3.2.1 on 2024-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
