# Generated by Django 5.0.2 on 2025-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='processed',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
